/**
 * Renderer — generates markdown output from canonical model.
 * Produces final_specification.md and per-section markdown files.
 */

import { CanonicalProduct } from '../schemas/canonical';
import { TraceabilityMatrix } from './traceability_engine';
import { CrossValidationResult } from './cross_validator';

export function renderFinalSpecification(
  product: CanonicalProduct,
  traceability: TraceabilityMatrix,
  validation: CrossValidationResult,
): string {
  const lines: string[] = [];

  // Title
  lines.push(`# ${product.title} — Specification`);
  lines.push('');
  lines.push(`> Generated by SpecMaster`);
  lines.push('');

  // Product Overview
  lines.push('## 1. Product Overview');
  lines.push('');
  lines.push(`**Product ID:** ${product.product_id}`);
  lines.push('');
  lines.push(product.summary);
  lines.push('');

  // Vision
  if (product.vision) {
    lines.push('### Vision');
    lines.push('');
    lines.push(product.vision);
    lines.push('');
  }

  // Goals / Non-Goals
  lines.push('## 2. Goals');
  lines.push('');
  for (const goal of product.goals) {
    lines.push(`- ${goal}`);
  }
  lines.push('');

  if (product.non_goals.length > 0) {
    lines.push('### Non-Goals');
    lines.push('');
    for (const ng of product.non_goals) {
      lines.push(`- ${ng}`);
    }
    lines.push('');
  }

  // Personas
  if (product.personas.length > 0) {
    lines.push('## 3. Personas');
    lines.push('');
    for (const persona of product.personas) {
      lines.push(`### ${persona.name}`);
      lines.push('');
      lines.push(persona.description);
      lines.push('');
      if (persona.goals.length > 0) {
        lines.push('**Goals:**');
        for (const g of persona.goals) lines.push(`- ${g}`);
        lines.push('');
      }
      if (persona.pain_points.length > 0) {
        lines.push('**Pain Points:**');
        for (const p of persona.pain_points) lines.push(`- ${p}`);
        lines.push('');
      }
    }
  }

  // Domain Model
  if (product.domain_model) {
    lines.push('## 4. Domain Model');
    lines.push('');
    lines.push(product.domain_model);
    lines.push('');
  }

  // Release Plan
  if (product.release_plan.length > 0) {
    lines.push('## 5. Release Plan');
    lines.push('');
    for (const release of product.release_plan) {
      lines.push(`### ${release.version}`);
      lines.push('');
      lines.push(release.description);
      lines.push('');
      lines.push(`**Rationale:** ${release.rationale}`);
      lines.push('');
      lines.push('**Features:**');
      for (const fId of release.feature_ids) {
        const f = product.features.find(ft => ft.feature_id === fId);
        lines.push(`- ${fId}: ${f?.title || 'Unknown'}`);
      }
      lines.push('');
    }
  }

  // Features
  lines.push('## 6. Features');
  lines.push('');
  for (const feature of product.features) {
    lines.push(`### ${feature.feature_id}: ${feature.title}`);
    lines.push('');
    lines.push(feature.description);
    lines.push('');
    lines.push(`| Field | Value |`);
    lines.push(`|-------|-------|`);
    lines.push(`| Priority | ${feature.priority} |`);
    lines.push(`| Release | ${feature.release_target || 'TBD'} |`);
    lines.push(`| Business Value | ${feature.business_value} |`);
    lines.push(`| User Value | ${feature.user_value} |`);
    lines.push(`| Confidence | ${feature.confidence_score} |`);
    lines.push(`| Source | ${feature.source_type} |`);
    lines.push('');
  }

  // User Stories
  lines.push('## 7. User Stories');
  lines.push('');
  for (const feature of product.features) {
    for (const story of feature.user_stories) {
      lines.push(`### ${story.story_id}: ${story.title}`);
      lines.push('');
      lines.push(`**Feature:** ${feature.feature_id} — ${feature.title}`);
      lines.push('');
      lines.push(`> As a ${story.as_a}, I want ${story.i_want}, so that ${story.so_that}.`);
      lines.push('');
      if (story.acceptance_intent) {
        lines.push(`**Acceptance Intent:** ${story.acceptance_intent}`);
        lines.push('');
      }
      lines.push(`**Confidence:** ${story.confidence_score} | **Source:** ${story.source_type}`);
      lines.push('');
    }
  }

  // User Flows
  lines.push('## 8. User Flows');
  lines.push('');
  for (const feature of product.features) {
    for (const story of feature.user_stories) {
      for (const flow of story.user_flows) {
        lines.push(`### ${flow.flow_id}: ${flow.title}`);
        lines.push('');
        lines.push(`**Story:** ${story.story_id} — ${story.title}`);
        lines.push('');
        lines.push(flow.description);
        lines.push('');
        lines.push('**Main Path:**');
        for (let i = 0; i < flow.main_path.length; i++) {
          lines.push(`${i + 1}. ${flow.main_path[i]}`);
        }
        lines.push('');
        if (flow.alternate_paths.length > 0) {
          lines.push('**Alternate Paths:**');
          for (const path of flow.alternate_paths) {
            lines.push(`- ${path.join(' → ')}`);
          }
          lines.push('');
        }
        if (flow.error_paths.length > 0) {
          lines.push('**Error Paths:**');
          for (const path of flow.error_paths) {
            lines.push(`- ${path.join(' → ')}`);
          }
          lines.push('');
        }
        if (flow.mermaid) {
          lines.push('**Diagram:**');
          lines.push('```mermaid');
          lines.push(flow.mermaid);
          lines.push('```');
          lines.push('');
        }
      }
    }
  }

  // Use Cases
  lines.push('## 9. Use Cases');
  lines.push('');
  for (const feature of product.features) {
    for (const story of feature.user_stories) {
      for (const flow of story.user_flows) {
        for (const uc of flow.use_cases) {
          lines.push(`### ${uc.use_case_id}: ${uc.title}`);
          lines.push('');
          lines.push(`**Flow:** ${flow.flow_id} — ${flow.title}`);
          lines.push('');
          lines.push(uc.description);
          lines.push('');
          lines.push(`**Actors:** ${uc.actors.join(', ')}`);
          lines.push(`**Trigger:** ${uc.trigger}`);
          lines.push('');
          lines.push(`- **Given:** ${uc.given}`);
          lines.push(`- **When:** ${uc.when}`);
          lines.push(`- **Then:** ${uc.then}`);
          lines.push('');
          if (uc.alternate_cases.length > 0) {
            lines.push('**Alternate Cases:**');
            for (const ac of uc.alternate_cases) lines.push(`- ${ac}`);
            lines.push('');
          }
          if (uc.error_cases.length > 0) {
            lines.push('**Error Cases:**');
            for (const ec of uc.error_cases) lines.push(`- ${ec}`);
            lines.push('');
          }
        }
      }
    }
  }

  // Functional Requirements
  lines.push('## 10. Functional Requirements');
  lines.push('');
  lines.push('| ID | Title | Statement | Priority | Verification |');
  lines.push('|----|-------|-----------|----------|--------------|');
  for (const feature of product.features) {
    for (const story of feature.user_stories) {
      for (const flow of story.user_flows) {
        for (const uc of flow.use_cases) {
          for (const fr of uc.functional_requirements) {
            lines.push(`| ${fr.requirement_id} | ${fr.title} | ${fr.statement} | ${fr.priority} | ${fr.verification_method} |`);
          }
        }
      }
    }
  }
  lines.push('');

  // Non-Functional Requirements
  lines.push('## 11. Non-Functional Requirements');
  lines.push('');
  lines.push('| ID | Category | Title | Statement | Measurable Criteria | Priority |');
  lines.push('|----|----------|-------|-----------|--------------------| ---------|');
  for (const feature of product.features) {
    for (const story of feature.user_stories) {
      for (const flow of story.user_flows) {
        for (const uc of flow.use_cases) {
          for (const nfr of uc.non_functional_requirements) {
            lines.push(`| ${nfr.requirement_id} | ${nfr.category} | ${nfr.title} | ${nfr.statement} | ${nfr.measurable_criteria} | ${nfr.priority} |`);
          }
        }
      }
    }
  }
  lines.push('');

  // Assumptions
  lines.push('## 12. Assumptions');
  lines.push('');
  for (const a of validation.assumptions) {
    lines.push(`- ${a}`);
  }
  lines.push('');

  // Open Questions
  lines.push('## 13. Open Questions');
  lines.push('');
  for (const q of validation.unresolved_items) {
    lines.push(`- ${q}`);
  }
  lines.push('');

  // Traceability Summary
  lines.push('## 14. Traceability Summary');
  lines.push('');
  lines.push('| Feature | Story | Flow | Use Case | Requirements |');
  lines.push('|---------|-------|------|----------|-------------|');
  for (const entry of traceability.entries) {
    lines.push(`| ${entry.feature_id} | ${entry.story_id} | ${entry.flow_id} | ${entry.use_case_id} | ${entry.requirement_ids.join(', ')} |`);
  }
  lines.push('');

  if (traceability.orphan_features.length > 0) {
    lines.push('### Orphan Features (no stories)');
    for (const id of traceability.orphan_features) lines.push(`- ${id}`);
    lines.push('');
  }

  // Validation Issues
  if (validation.issues.length > 0) {
    lines.push('### Validation Issues');
    lines.push('');
    lines.push('| Level | Entity | Type | Severity | Description |');
    lines.push('|-------|--------|------|----------|-------------|');
    for (const issue of validation.issues) {
      lines.push(`| ${issue.level} | ${issue.entity_id} | ${issue.issue_type} | ${issue.severity} | ${issue.description} |`);
    }
    lines.push('');
  }

  // Coverage Summary
  lines.push('### Coverage');
  lines.push('');
  const c = validation.coverage;
  lines.push(`- Features with stories: ${c.features_with_stories}/${c.features_with_stories + c.features_without_stories}`);
  lines.push(`- Stories with flows: ${c.stories_with_flows}/${c.stories_with_flows + c.stories_without_flows}`);
  lines.push(`- Flows with use cases: ${c.flows_with_use_cases}/${c.flows_with_use_cases + c.flows_without_use_cases}`);
  lines.push(`- Use cases with FR: ${c.use_cases_with_fr}/${c.use_cases_with_fr + c.use_cases_without_fr}`);
  lines.push(`- Use cases with NFR: ${c.use_cases_with_nfr}/${c.use_cases_with_nfr + c.use_cases_without_nfr}`);
  lines.push('');

  return lines.join('\n');
}

export function renderFeaturesMarkdown(product: CanonicalProduct): string {
  const lines: string[] = ['# Features', ''];
  for (const f of product.features) {
    lines.push(`## ${f.feature_id}: ${f.title}`);
    lines.push('');
    lines.push(f.description);
    lines.push('');
    lines.push(`- **Priority:** ${f.priority}`);
    lines.push(`- **Release:** ${f.release_target || 'TBD'}`);
    lines.push(`- **Business Value:** ${f.business_value}`);
    lines.push(`- **User Value:** ${f.user_value}`);
    lines.push(`- **Confidence:** ${f.confidence_score} (${f.source_type})`);
    lines.push('');
  }
  return lines.join('\n');
}

export function renderStoriesMarkdown(product: CanonicalProduct): string {
  const lines: string[] = ['# User Stories', ''];
  for (const f of product.features) {
    lines.push(`## Feature: ${f.feature_id} — ${f.title}`);
    lines.push('');
    for (const s of f.user_stories) {
      lines.push(`### ${s.story_id}: ${s.title}`);
      lines.push('');
      lines.push(`> As a ${s.as_a}, I want ${s.i_want}, so that ${s.so_that}.`);
      lines.push('');
      if (s.acceptance_intent) lines.push(`**Acceptance:** ${s.acceptance_intent}`);
      lines.push(`**Confidence:** ${s.confidence_score} (${s.source_type})`);
      lines.push('');
    }
  }
  return lines.join('\n');
}

export function renderUseCasesMarkdown(product: CanonicalProduct): string {
  const lines: string[] = ['# Use Cases', ''];
  for (const f of product.features) {
    for (const s of f.user_stories) {
      for (const fl of s.user_flows) {
        for (const uc of fl.use_cases) {
          lines.push(`## ${uc.use_case_id}: ${uc.title}`);
          lines.push('');
          lines.push(uc.description);
          lines.push('');
          lines.push(`- **Given:** ${uc.given}`);
          lines.push(`- **When:** ${uc.when}`);
          lines.push(`- **Then:** ${uc.then}`);
          lines.push('');
        }
      }
    }
  }
  return lines.join('\n');
}

export function renderRequirementsMarkdown(product: CanonicalProduct): string {
  const lines: string[] = ['# Requirements', ''];

  lines.push('## Functional Requirements');
  lines.push('');
  for (const f of product.features) {
    for (const s of f.user_stories) {
      for (const fl of s.user_flows) {
        for (const uc of fl.use_cases) {
          for (const fr of uc.functional_requirements) {
            lines.push(`### ${fr.requirement_id}: ${fr.title}`);
            lines.push('');
            lines.push(fr.statement);
            lines.push('');
            lines.push(`- **Priority:** ${fr.priority}`);
            lines.push(`- **Verification:** ${fr.verification_method}`);
            lines.push(`- **Rationale:** ${fr.rationale}`);
            lines.push('');
          }
        }
      }
    }
  }

  lines.push('## Non-Functional Requirements');
  lines.push('');
  for (const f of product.features) {
    for (const s of f.user_stories) {
      for (const fl of s.user_flows) {
        for (const uc of fl.use_cases) {
          for (const nfr of uc.non_functional_requirements) {
            lines.push(`### ${nfr.requirement_id}: ${nfr.title} [${nfr.category}]`);
            lines.push('');
            lines.push(nfr.statement);
            lines.push('');
            lines.push(`- **Measurable Criteria:** ${nfr.measurable_criteria}`);
            lines.push(`- **Priority:** ${nfr.priority}`);
            lines.push(`- **Verification:** ${nfr.verification_method}`);
            lines.push('');
          }
        }
      }
    }
  }

  return lines.join('\n');
}

export function renderReleasePlanMarkdown(product: CanonicalProduct): string {
  const lines: string[] = ['# Release Plan', ''];
  for (const r of product.release_plan) {
    lines.push(`## ${r.version}`);
    lines.push('');
    lines.push(r.description);
    lines.push('');
    lines.push(`**Rationale:** ${r.rationale}`);
    lines.push('');
    lines.push('**Features:**');
    for (const fId of r.feature_ids) {
      const f = product.features.find(ft => ft.feature_id === fId);
      lines.push(`- ${fId}: ${f?.title || 'Unknown'}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}
